train:
  log_interval: 200
  eval_interval: 1000
  seed: 1234
  epochs: 10000
  learning_rate: 0.0002
  betas: [0.8, 0.99]
  eps: 1.0e-09
  batch_size: 64
  fp16_run: true
  lr_decay: 0.999875
  segment_size: 8192
  init_lr_ratio: 1
  warmup_epochs: 0
  c_mel: 45
  c_kl: 1

evaluate:
  n_fft: 2048 # ! >= 32 * n_mels
  hop_length: 256
  win_length: 1024
  n_mels: 80
  f_min: 0
  f_max:

data:
  training_files: datasets/vctk_base/filelists/vctk_audio_sid_text_train_filelist.txt.cleaned
  validation_files: datasets/vctk_base/filelists/vctk_audio_sid_text_val_filelist.txt.cleaned
  text_cleaners:
    - phonemize_text
  bits_per_sample: 16
  sample_rate: 22050
  n_fft: 32768 # ! >= 32 * n_mels
  hop_length: 256
  win_length: 1024
  n_mels: 512
  f_min: 0
  f_max:
  n_speakers: 109
  cleaned_text: true
  use_mel: true
  add_blank: false

model:
  inter_channels: 192
  hidden_channels: 192
  filter_channels: 768
  n_heads: 2
  n_layers: 6
  speaker_cond_layer: 3 # 0 to disable speaker conditioning
  kernel_size: 3
  p_dropout: 0.1
  resblock: "1"
  resblock_kernel_sizes: [3, 7, 11]
  resblock_dilation_sizes: [[1, 3, 5], [1, 3, 5], [1, 3, 5]]
  upsample_rates: [8, 8, 2, 2]
  upsample_initial_channel: 512
  upsample_kernel_sizes: [16, 16, 4, 4]
  n_layers_q: 3
  gin_channels: 256
  mas_noise_scale: 0.01 # 0.0 to disable Gaussian noise in MAS
  mas_noise_scale_decay: 2.0e-06
  use_spectral_norm: false
  use_transformer_flow: true
